// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: proto/url_shortener.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input *ShortenRequestV1_ShortenInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ShortenRequestV1) Reset() {
	*x = ShortenRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequestV1) ProtoMessage() {}

func (x *ShortenRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequestV1.ProtoReflect.Descriptor instead.
func (*ShortenRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequestV1) GetInput() *ShortenRequestV1_ShortenInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ShortenResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output *ShortenResponseV1_ShortenOutput `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ShortenResponseV1) Reset() {
	*x = ShortenResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponseV1) ProtoMessage() {}

func (x *ShortenResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponseV1.ProtoReflect.Descriptor instead.
func (*ShortenResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponseV1) GetOutput() *ShortenResponseV1_ShortenOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type ShortenBatchRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input []*ShortenBatchRequestV1_ShortenBatchInput `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
}

func (x *ShortenBatchRequestV1) Reset() {
	*x = ShortenBatchRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequestV1) ProtoMessage() {}

func (x *ShortenBatchRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequestV1.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenBatchRequestV1) GetInput() []*ShortenBatchRequestV1_ShortenBatchInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type ShortenBatchResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output []*ShortenBatchResponseV1_ShortenBatchOutput `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
}

func (x *ShortenBatchResponseV1) Reset() {
	*x = ShortenBatchResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponseV1) ProtoMessage() {}

func (x *ShortenBatchResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponseV1.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenBatchResponseV1) GetOutput() []*ShortenBatchResponseV1_ShortenBatchOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type GetRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *GetRequestV1) Reset() {
	*x = GetRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestV1) ProtoMessage() {}

func (x *GetRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestV1.ProtoReflect.Descriptor instead.
func (*GetRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequestV1) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *GetResponseV1) Reset() {
	*x = GetResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseV1) ProtoMessage() {}

func (x *GetResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseV1.ProtoReflect.Descriptor instead.
func (*GetResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponseV1) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type PingRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequestV1) Reset() {
	*x = PingRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequestV1) ProtoMessage() {}

func (x *PingRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequestV1.ProtoReflect.Descriptor instead.
func (*PingRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{6}
}

type PingResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PingResponseV1) Reset() {
	*x = PingResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponseV1) ProtoMessage() {}

func (x *PingResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponseV1.ProtoReflect.Descriptor instead.
func (*PingResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponseV1) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type UserUrlsRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserUrlsRequestV1) Reset() {
	*x = UserUrlsRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsRequestV1) ProtoMessage() {}

func (x *UserUrlsRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsRequestV1.ProtoReflect.Descriptor instead.
func (*UserUrlsRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{8}
}

type UserUrlsResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output []*UserUrlsResponseV1_UserUrls `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
}

func (x *UserUrlsResponseV1) Reset() {
	*x = UserUrlsResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsResponseV1) ProtoMessage() {}

func (x *UserUrlsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsResponseV1.ProtoReflect.Descriptor instead.
func (*UserUrlsResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UserUrlsResponseV1) GetOutput() []*UserUrlsResponseV1_UserUrls {
	if x != nil {
		return x.Output
	}
	return nil
}

type UserUrlsDeleteRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *UserUrlsDeleteRequestV1) Reset() {
	*x = UserUrlsDeleteRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsDeleteRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsDeleteRequestV1) ProtoMessage() {}

func (x *UserUrlsDeleteRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsDeleteRequestV1.ProtoReflect.Descriptor instead.
func (*UserUrlsDeleteRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *UserUrlsDeleteRequestV1) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserUrlsDeleteResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UserUrlsDeleteResponseV1) Reset() {
	*x = UserUrlsDeleteResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsDeleteResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsDeleteResponseV1) ProtoMessage() {}

func (x *UserUrlsDeleteResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsDeleteResponseV1.ProtoReflect.Descriptor instead.
func (*UserUrlsDeleteResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *UserUrlsDeleteResponseV1) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type StatsRequestV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatsRequestV1) Reset() {
	*x = StatsRequestV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsRequestV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequestV1) ProtoMessage() {}

func (x *StatsRequestV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequestV1.ProtoReflect.Descriptor instead.
func (*StatsRequestV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{12}
}

type StatsResponseV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int64 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int64 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *StatsResponseV1) Reset() {
	*x = StatsResponseV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponseV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponseV1) ProtoMessage() {}

func (x *StatsResponseV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponseV1.ProtoReflect.Descriptor instead.
func (*StatsResponseV1) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *StatsResponseV1) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponseV1) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

type ShortenRequestV1_ShortenInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortenRequestV1_ShortenInput) Reset() {
	*x = ShortenRequestV1_ShortenInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenRequestV1_ShortenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequestV1_ShortenInput) ProtoMessage() {}

func (x *ShortenRequestV1_ShortenInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequestV1_ShortenInput.ProtoReflect.Descriptor instead.
func (*ShortenRequestV1_ShortenInput) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ShortenRequestV1_ShortenInput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponseV1_ShortenOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenResponseV1_ShortenOutput) Reset() {
	*x = ShortenResponseV1_ShortenOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenResponseV1_ShortenOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponseV1_ShortenOutput) ProtoMessage() {}

func (x *ShortenResponseV1_ShortenOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponseV1_ShortenOutput.ProtoReflect.Descriptor instead.
func (*ShortenResponseV1_ShortenOutput) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ShortenResponseV1_ShortenOutput) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchRequestV1_ShortenBatchInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenBatchRequestV1_ShortenBatchInput) Reset() {
	*x = ShortenBatchRequestV1_ShortenBatchInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchRequestV1_ShortenBatchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchRequestV1_ShortenBatchInput) ProtoMessage() {}

func (x *ShortenBatchRequestV1_ShortenBatchInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchRequestV1_ShortenBatchInput.ProtoReflect.Descriptor instead.
func (*ShortenBatchRequestV1_ShortenBatchInput) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ShortenBatchRequestV1_ShortenBatchInput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchRequestV1_ShortenBatchInput) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchResponseV1_ShortenBatchOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenBatchResponseV1_ShortenBatchOutput) Reset() {
	*x = ShortenBatchResponseV1_ShortenBatchOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchResponseV1_ShortenBatchOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchResponseV1_ShortenBatchOutput) ProtoMessage() {}

func (x *ShortenBatchResponseV1_ShortenBatchOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchResponseV1_ShortenBatchOutput.ProtoReflect.Descriptor instead.
func (*ShortenBatchResponseV1_ShortenBatchOutput) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ShortenBatchResponseV1_ShortenBatchOutput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchResponseV1_ShortenBatchOutput) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UserUrlsResponseV1_UserUrls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *UserUrlsResponseV1_UserUrls) Reset() {
	*x = UserUrlsResponseV1_UserUrls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_url_shortener_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUrlsResponseV1_UserUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUrlsResponseV1_UserUrls) ProtoMessage() {}

func (x *UserUrlsResponseV1_UserUrls) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_shortener_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUrlsResponseV1_UserUrls.ProtoReflect.Descriptor instead.
func (*UserUrlsResponseV1_UserUrls) Descriptor() ([]byte, []int) {
	return file_proto_url_shortener_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UserUrlsResponseV1_UserUrls) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserUrlsResponseV1_UserUrls) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_proto_url_shortener_proto protoreflect.FileDescriptor

var file_proto_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x70, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x3a, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x20, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x3e, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x1a, 0x2c, 0x0a, 0x0d, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0xbc, 0x01, 0x0a, 0x15, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x12, 0x44, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x5d, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x12, 0x48, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x1a, 0x58, 0x0a, 0x12,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x31, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x3a,
	0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72,
	0x6c, 0x73, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x1a, 0x4a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72,
	0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x31, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x32, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x22, 0x3b, 0x0a, 0x0f, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0xe3, 0x03, 0x0a, 0x15, 0x55, 0x52, 0x4c,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x56, 0x31, 0x12, 0x3e, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x56, 0x31, 0x12,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x56, 0x31, 0x12, 0x4d, 0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x56, 0x31, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x56, 0x31, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56,
	0x31, 0x12, 0x32, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x56, 0x31, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x35, 0x0a, 0x06, 0x50, 0x69, 0x6e, 0x67, 0x56, 0x31, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12, 0x41, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x56, 0x31, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x31, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x12,
	0x53, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x56, 0x31, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x56, 0x31, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x72, 0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x31, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x74, 0x73, 0x56, 0x31, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x31, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x31, 0x42, 0x49,
	0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6a, 0x75,
	0x67, 0x61, 0x6c, 0x75, 0x73, 0x68, 0x6b, 0x69, 0x6e, 0x2f, 0x75, 0x72, 0x6c, 0x2d, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x79, 0x64, 0x78, 0x2f, 0x75, 0x72, 0x6c, 0x2d, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_url_shortener_proto_rawDescOnce sync.Once
	file_proto_url_shortener_proto_rawDescData = file_proto_url_shortener_proto_rawDesc
)

func file_proto_url_shortener_proto_rawDescGZIP() []byte {
	file_proto_url_shortener_proto_rawDescOnce.Do(func() {
		file_proto_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_url_shortener_proto_rawDescData)
	})
	return file_proto_url_shortener_proto_rawDescData
}

var file_proto_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_url_shortener_proto_goTypes = []any{
	(*ShortenRequestV1)(nil),                          // 0: proto.ShortenRequestV1
	(*ShortenResponseV1)(nil),                         // 1: proto.ShortenResponseV1
	(*ShortenBatchRequestV1)(nil),                     // 2: proto.ShortenBatchRequestV1
	(*ShortenBatchResponseV1)(nil),                    // 3: proto.ShortenBatchResponseV1
	(*GetRequestV1)(nil),                              // 4: proto.GetRequestV1
	(*GetResponseV1)(nil),                             // 5: proto.GetResponseV1
	(*PingRequestV1)(nil),                             // 6: proto.PingRequestV1
	(*PingResponseV1)(nil),                            // 7: proto.PingResponseV1
	(*UserUrlsRequestV1)(nil),                         // 8: proto.UserUrlsRequestV1
	(*UserUrlsResponseV1)(nil),                        // 9: proto.UserUrlsResponseV1
	(*UserUrlsDeleteRequestV1)(nil),                   // 10: proto.UserUrlsDeleteRequestV1
	(*UserUrlsDeleteResponseV1)(nil),                  // 11: proto.UserUrlsDeleteResponseV1
	(*StatsRequestV1)(nil),                            // 12: proto.StatsRequestV1
	(*StatsResponseV1)(nil),                           // 13: proto.StatsResponseV1
	(*ShortenRequestV1_ShortenInput)(nil),             // 14: proto.ShortenRequestV1.ShortenInput
	(*ShortenResponseV1_ShortenOutput)(nil),           // 15: proto.ShortenResponseV1.ShortenOutput
	(*ShortenBatchRequestV1_ShortenBatchInput)(nil),   // 16: proto.ShortenBatchRequestV1.ShortenBatchInput
	(*ShortenBatchResponseV1_ShortenBatchOutput)(nil), // 17: proto.ShortenBatchResponseV1.ShortenBatchOutput
	(*UserUrlsResponseV1_UserUrls)(nil),               // 18: proto.UserUrlsResponseV1.UserUrls
}
var file_proto_url_shortener_proto_depIdxs = []int32{
	14, // 0: proto.ShortenRequestV1.input:type_name -> proto.ShortenRequestV1.ShortenInput
	15, // 1: proto.ShortenResponseV1.output:type_name -> proto.ShortenResponseV1.ShortenOutput
	16, // 2: proto.ShortenBatchRequestV1.input:type_name -> proto.ShortenBatchRequestV1.ShortenBatchInput
	17, // 3: proto.ShortenBatchResponseV1.output:type_name -> proto.ShortenBatchResponseV1.ShortenBatchOutput
	18, // 4: proto.UserUrlsResponseV1.output:type_name -> proto.UserUrlsResponseV1.UserUrls
	0,  // 5: proto.URLShortenerServiceV1.ShortenV1:input_type -> proto.ShortenRequestV1
	2,  // 6: proto.URLShortenerServiceV1.ShortenBatchV1:input_type -> proto.ShortenBatchRequestV1
	4,  // 7: proto.URLShortenerServiceV1.GetV1:input_type -> proto.GetRequestV1
	6,  // 8: proto.URLShortenerServiceV1.PingV1:input_type -> proto.PingRequestV1
	8,  // 9: proto.URLShortenerServiceV1.UserUrlsV1:input_type -> proto.UserUrlsRequestV1
	10, // 10: proto.URLShortenerServiceV1.UserUrlsDeleteV1:input_type -> proto.UserUrlsDeleteRequestV1
	12, // 11: proto.URLShortenerServiceV1.StatsV1:input_type -> proto.StatsRequestV1
	1,  // 12: proto.URLShortenerServiceV1.ShortenV1:output_type -> proto.ShortenResponseV1
	3,  // 13: proto.URLShortenerServiceV1.ShortenBatchV1:output_type -> proto.ShortenBatchResponseV1
	5,  // 14: proto.URLShortenerServiceV1.GetV1:output_type -> proto.GetResponseV1
	7,  // 15: proto.URLShortenerServiceV1.PingV1:output_type -> proto.PingResponseV1
	9,  // 16: proto.URLShortenerServiceV1.UserUrlsV1:output_type -> proto.UserUrlsResponseV1
	11, // 17: proto.URLShortenerServiceV1.UserUrlsDeleteV1:output_type -> proto.UserUrlsDeleteResponseV1
	13, // 18: proto.URLShortenerServiceV1.StatsV1:output_type -> proto.StatsResponseV1
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_url_shortener_proto_init() }
func file_proto_url_shortener_proto_init() {
	if File_proto_url_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_url_shortener_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UserUrlsRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UserUrlsResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UserUrlsDeleteRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UserUrlsDeleteResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StatsRequestV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*StatsResponseV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenRequestV1_ShortenInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenResponseV1_ShortenOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchRequestV1_ShortenBatchInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchResponseV1_ShortenBatchOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_url_shortener_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UserUrlsResponseV1_UserUrls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_url_shortener_proto_goTypes,
		DependencyIndexes: file_proto_url_shortener_proto_depIdxs,
		MessageInfos:      file_proto_url_shortener_proto_msgTypes,
	}.Build()
	File_proto_url_shortener_proto = out.File
	file_proto_url_shortener_proto_rawDesc = nil
	file_proto_url_shortener_proto_goTypes = nil
	file_proto_url_shortener_proto_depIdxs = nil
}
